# permissions for end users to edit demomicroservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: demomicroservice-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: example
    app.kubernetes.io/part-of: example
    app.kubernetes.io/managed-by: kustomize
  name: demomicroservice-editor-role
rules:
- apiGroups:
  - devops.my.domain
  resources:
  - demomicroservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.my.domain
  resources:
  - demomicroservices/status
  verbs:
  - get
